import React from "react";

export default function IOFilmOutline(props:{size?:number; width?:number;height?:number}) {
let {width,height,size}=props;
if(size!==undefined){width=size;height=size;}
if(width===undefined && height===undefined){width=16;height=16;}

  return (
    <svg className="glx--icon glx-io-icon" width={ width } height={ height }
      xmlns="http://www.w3.org/2000/svg"
      
      
      viewBox="0 0 512 512"
    >
      <rect
        width="416"
        height="320"
        x="48"
        y="96"
        fill="none"
        stroke="#000"
        strokeLinejoin="round"
        strokeWidth="32"
        rx="28"
        ry="28"
      ></rect>
      <rect
        width="80"
        height="80"
        x="384"
        y="336"
        fill="none"
        stroke="#000"
        strokeLinejoin="round"
        strokeWidth="32"
        rx="28"
        ry="28"
      ></rect>
      <rect
        width="80"
        height="80"
        x="384"
        y="256"
        fill="none"
        stroke="#000"
        strokeLinejoin="round"
        strokeWidth="32"
        rx="28"
        ry="28"
      ></rect>
      <rect
        width="80"
        height="80"
        x="384"
        y="176"
        fill="none"
        stroke="#000"
        strokeLinejoin="round"
        strokeWidth="32"
        rx="28"
        ry="28"
      ></rect>
      <rect
        width="80"
        height="80"
        x="384"
        y="96"
        fill="none"
        stroke="#000"
        strokeLinejoin="round"
        strokeWidth="32"
        rx="28"
        ry="28"
      ></rect>
      <rect
        width="80"
        height="80"
        x="48"
        y="336"
        fill="none"
        stroke="#000"
        strokeLinejoin="round"
        strokeWidth="32"
        rx="28"
        ry="28"
      ></rect>
      <rect
        width="80"
        height="80"
        x="48"
        y="256"
        fill="none"
        stroke="#000"
        strokeLinejoin="round"
        strokeWidth="32"
        rx="28"
        ry="28"
      ></rect>
      <rect
        width="80"
        height="80"
        x="48"
        y="176"
        fill="none"
        stroke="#000"
        strokeLinejoin="round"
        strokeWidth="32"
        rx="28"
        ry="28"
      ></rect>
      <rect
        width="80"
        height="80"
        x="48"
        y="96"
        fill="none"
        stroke="#000"
        strokeLinejoin="round"
        strokeWidth="32"
        rx="28"
        ry="28"
      ></rect>
      <rect
        width="256"
        height="160"
        x="128"
        y="96"
        fill="none"
        stroke="#000"
        strokeLinejoin="round"
        strokeWidth="32"
        rx="28"
        ry="28"
      ></rect>
      <rect
        width="256"
        height="160"
        x="128"
        y="256"
        fill="none"
        stroke="#000"
        strokeLinejoin="round"
        strokeWidth="32"
        rx="28"
        ry="28"
      ></rect>
    </svg>
  );
}


